### ISSUE TITLE
Update Medicare SAF Connector

### ISSUE THREAD

**Issue by aneiderhiser** [tuva-health/medicare_saf_connector#12]
**general things:**
- data_source: currently this is "saf".  Let's change it to "Medicare LDS"

**master_beneficiary_summary:**
- birth_date: Currently birth_date is being calculated as the current year minus the patient's age.  However this dataset is from 2020, so the patient's age is from the year 2020, not the current year.
- medicare_state_fips: currently this seed ships w/ the connector.  remove the seed and use terminology instead.

**carrier claims:**
- billing_npi: missing on carrier claims.  facility_npi is populated with org_npi_num.  I wonder if this should be mapped to billing_npi instead, because I would expect prof claims to have a rendering and org npi, but not facility.
- allowed_amount: charges are being mapped to this - should be null instead unless we have actual allowed amounts somewhere.

**dme claims:**
- rendering_npi: prvdr_npi is being mapped to this.  my guess is that these are mostly organizations.  confirm by googling and if so change to billing_provider_npi
- allowed_amount: similar to carrier claims - line_alowd_chrg_amt is being mapped here.  This is a charge not an allowed_amount.  Allowed_amount is a payment (paid_amount + patient portion).

**home health:**
- discharge_status: currently null but this exists in raw data as PTNT_DSCHRG_STUS_CD
- charge_amount: currently being pulled from the line.  if the line values don't equal header values or if the line values are mostly zero then we should change this to pulling from the header CLM_TOT_CHRG_AMT and assign to line number 1.
- paid_amount: same as charge_amount
- billing_npi: this is null but i think this should be ORG_NPI_NUM.  Currently ORG_NPI_NUM is mapped to facility_npi.

**hospice:**
- discharge_status: currently null but this exists in raw data as PTNT_DSCHRG_STUS_CD
- billing_npi: this is null but i think this should be ORG_NPI_NUM.  Currently ORG_NPI_NUM is mapped to facility_npi.

**Comment by aneiderhiser** [comment]
The master_beneficiary_summary table has a column called reference_year that could be used instead.

**Comment by thutuva** [comment]
These issues have been mostly resolved and attached to a PR.   The only issue not addressed was birth_date becuase it is not using the current year - age to calculate birth_date.  Year is actually reference year which is the year of the data set.  So subtracting age from reference year is accurate to calculate.
